#!/usr/bin/env python
# Copyright (c) 2016 The SAYCBridge Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import print_function
from builtins import range
from collections import defaultdict
import ijson
import json
import sys

def main():
  data = {}

  for filename in sys.argv[1:]:
    with open(filename) as f:
      for board in ijson.items(f, "item"):
        for index in range(0, len(board['calls'])):
          if index < 2:
            state = "Start"
          else:
            state = "%s-%s" % (board['calls'][index-2], board['rules'][index-2])
          if index > 0 and board['calls'][index-1] != "P":
            state += "-Interference"
          state_data = data.setdefault(state, defaultdict(lambda: 0))
          state_data[board['calls'][index]] += 1

  print(json.dumps(data, sort_keys=True, indent=4, separators=(',', ': ')))

if __name__ == "__main__":
      main()
