#!/usr/bin/env python
# Copyright (c) 2016 The SAYCBridge Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import sys
import find_src
import logging
import json
import argparse
import datetime

from z3b.bidder import Bidder
from core.board import Board
from core.call import Pass

log = logging.getLogger(__name__)

class CompileExplorer:
    def _bid_board(self, board, bidder):
        result = {}
        result['board'] = str(board.identifier)
        result['calls'] = []
        result['rules'] = []
        while not board.call_history.is_complete():
            position_to_call = board.call_history.position_to_call().index
            hand = board.deal.hands[position_to_call]
            selection = bidder.call_selection_for(hand, board.call_history)
            if not selection:
                log.warn("None Call for: %s" % board.identifier)
                call = Pass()
                rule = None
            else:
                call = selection.call
                rule = selection.rule
            board.call_history.calls.append(call)
            result['calls'].append(str(call))
            result['rules'].append(str(rule))
        return result

    def configure_logging(self, verbose):
        handler = logging.StreamHandler(sys.stderr)
        formatter = logging.Formatter("%(levelname)-8s: %(message)s")
        handler.setFormatter(formatter)

        logger = logging.getLogger()
        logger.addHandler(handler)
        if verbose:
            logger.setLevel(logging.NOTSET)

    def _bid_boards_into_file(self, count, results_file):
        bidder = Bidder()
        results_file.write('[')
        written = 0
        try:
            for _ in xrange(count):
                # This whole dance is to avoid ^C adding a trailing comma.
                result = self._bid_board(Board.random(), bidder)
                if written != 0:
                    results_file.write(',')
                results_file.write('\n')
                json.dump(result, results_file)
                written += 1
        except KeyboardInterrupt:
            print
            print "User Interrupted."
        results_file.write('\n]\n')
        return written

    def main(self, args):
        parser = argparse.ArgumentParser()
        parser.add_argument('output_path', type=str)
        parser.add_argument('count', type=int)
        parser.add_argument('--verbose', '-v')
        args = parser.parse_args()

        self.configure_logging(args.verbose)
        with open(args.output_path, 'w') as results_file:
            start = datetime.datetime.now()
            written_count = self._bid_boards_into_file(args.count, results_file)
            end = datetime.datetime.now()
            duration = round((end - start).total_seconds(), 1)
            print "%s results written to %s in %ss" % (written_count, args.output_path, duration)


if __name__ == '__main__':
    CompileExplorer().main(sys.argv[1:])
