#!/usr/bin/env python
# Copyright (c) 2013 The SAYCBridge Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import logging
import unittest2
import sys

import find_src
from factory import BidderFactory

# This import list is lame.  Other projects automagically know how
# to find _unittest.py files, perhaps we should do something similar:
# http://trac.webkit.org/browser/trunk/Tools/Scripts/webkitpy/test/finder.py

from core.tests.test_callhistory import *
from core.tests.test_call import *
from core.tests.test_board import *
from core.tests.test_deal import *
from core.tests.test_hand import *
from core.tests.test_position import *
from tests.harness import TestHarness


def configure_logging(is_verbose):
    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter("%(levelname)-8s: %(message)s")
    handler.setFormatter(formatter)

    logger = logging.getLogger()
    logger.addHandler(handler)
    if is_verbose:
        logger.setLevel(logging.NOTSET)


if __name__ == '__main__':
    # Logging is a big hack.
    is_verbose = '-v' in sys.argv
    configure_logging(is_verbose)

    sys.argv = BidderFactory.configure_from_args(sys.argv)

    if '-s' in sys.argv:
        sys.argv.remove('-s')
        TestHarness.use_multi_process = False

    if '-p' in sys.argv:
        sys.argv.remove('-p')
        import cProfile as profile
        profile.run("unittest2.main()", "profile")
        print "Use 'python -m pstats profile' to see results"
    else:
        try:
            unittest2.main()
        except KeyboardInterrupt:
            # Just quietly exit.
            pass
