#!/usr/bin/env python
# Copyright (c) 2013 The SAYCBridge Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from core.callhistory_unittest import *
from core.call_unittest import *
from core.board_unittest import *
from core.deal_unittest import *
from core.hand_unittest import *
from core.position_unittest import *
from core.sayc_unittest import *

from kbb.handconstraints_unittest import *
from kbb.semanticbids_unittest import *
from kbb.interpreter_unittest import *

from factory import BidderFactory

import logging
import unittest2
import sys


def configure_logging(is_verbose):
    handler = logging.StreamHandler(sys.stdout)
    formatter = logging.Formatter("%(levelname)-8s: %(message)s")
    handler.setFormatter(formatter)

    logger = logging.getLogger()
    logger.addHandler(handler)
    if is_verbose:
        logger.setLevel(logging.NOTSET)


if __name__ == '__main__':
    # Logging is a big hack.
    is_verbose = '-v' in sys.argv
    configure_logging(is_verbose)

    sys.argv = BidderFactory.configure_from_args(sys.argv)

    if '-p' in sys.argv:
        sys.argv.remove('-p')
        import cProfile as profile
        profile.run("unittest2.main()", "profile")
        print "Use 'python -m pstats profile' to see results"
    else:
        unittest2.main()
